# Generated by Django 4.2 on 2024-04-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kangmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kangmark',
            name='url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
